* Written by R;
*  write.foreign(data, "sasdata.txt", "sasdata.sas", package = "SAS") ;

DATA  data ;
LENGTH
 group_string $ 8
 pre_Qurepack_entered_INITIALS $ 7
 pre_Prev_Tx_Qure_enterd_INITIALS $ 7
 pre_EDS_entered_INITIALS $ 7
 pre_DECA_entered_INITIALS $ 7
 pre_MCHAT_entered_INITIALS $ 7
 pre_ECBI_entered_INITIALS $ 7
 pre_Mullen_entered_INITIALS $ 7
 post_Qurepack_entered_INITIALS $ 13
 post_DECA_entered_INITIALS $ 6
 post_ECBI_entered_INITIALS $ 6
 FU_Qurepack_entered_INITIALS $ 6
 FU_DECA_entered_INITIALS $ 6
 FU_ECBI_entered_INITIALS $ 6
 Pre_Ax_3_Date $ 5
 OCCmo $ 52
 OCCfa $ 31
 LANGspoken $ 10
 LANGspoken_other $ 17
 preCBCL24A $ 69
 preCBCL31A $ 63
 preCBCL32A $ 65
 preCBCL46A $ 50
 preCBCL54A $ 53
 preCBCL57A $ 54
 preCBCL65A $ 52
 preCBCL74A $ 66
 preCBCL76A $ 33
 preCBCL80A $ 81
 preCBCL92A $ 61
 preCBCL100A $ 102
 preBITSEA_PF8_details $ 117
 preBITSEA_PF36_details $ 166
 preBITSEA_PF37_details $ 107
 preBITSEA_PF41_details $ 69
 preBITSEA_PF42_details $ 119
 prePTQ_COS_Date $ 26
 prePTQ_COS_Length $ 26
 prePTQ_PCIT_Date $ 5
 prePTQ_PCIT_Length $ 5
 prePTQ_TiK_Date $ 5
 prePTQ_TiK_Length $ 5
 prePTQ_PPP_Date $ 12
 prePTQ_PPP_Length $ 26
 prePTQ_PT_Date $ 5
 prePTQ_PT_Length $ 5
 prePTQ_Other_Specify $ 27
 prePTQ_Other_Date $ 7
 prePTQ_Other_Length $ 36
 post_CBCL24A $ 109
 post_CBCL31A $ 73
 post_CBCL32A $ 137
 post_CBCL46A $ 19
 post_CBCL54A $ 45
 post_CBCL57A $ 22
 post_CBCL65A $ 158
 post_CBCL74A $ 124
 post_CBCL76A $ 193
 post_CBCL80A $ 137
 post_CBCL92A $ 327
 post_CBCL100A $ 102
 post_BITSEA_PF8des $ 30
 post_BITSEA_PF36desc $ 51
 post_BITSEA_PF37desc $ 22
 post_BITSEA_PF41 $ 6
 post_BITSEA_PF42desc $ 75
 FU_CBCL24A $ 98
 FU_CBCL31A $ 41
 FU_CBCL32A $ 170
 FU_CBCL46A $ 15
 FU_CBCL54A $ 39
 FU_CBCL57A $ 37
 FU_CBCL65A $ 32
 FU_CBCL74A $ 173
 FU_CBCL76A $ 20
 FU_CBCL80A $ 94
 FU_CBCL92A $ 36
 FU_CBCL100A $ 13
 FU_PTQ_COS_Date $ 12
 FU_PTQ_COS_Length $ 8
 FU_PTQ_PCIT_Date $ 15
 FU_PTQ_PCIT_Length $ 8
 FU_PTQ_TiK_Date $ 5
 FU_PTQ_TiK_Length $ 5
 FU_PTQ_PPP_Date $ 12
 FU_PTQ_PPP_Length $ 8
 FU_PTQ_PT_Date $ 39
 FU_PTQ_PT_Length $ 7
 FU_PTQ_Other_Specify $ 5
 FU_PTQ_Other_Date $ 5
 FU_PTQ_Other_Length $ 5
 Baseline_sensitivity_Coder $ 2
 SSP_Pre_Code_betty_gave $ 8
 SSP_Post__Code_betty_gave $ 7
;

INFORMAT
 Pre_Ax_1_Date
 Pre_Ax_2_Date
 Pre_Home_Visit_Date
 Date_ASD_Ax
 Date_Pre_questionnaires
 DOBchild
 DOBmo
 DOBfa
 YYMMDD10.
;

INFILE  "sasdata.txt" 
     DSD 
     LRECL= 8807 ;
INPUT
 ID
 group_string
 GROUP
 ASDcase
 Treatment_time_mins
 VIDEO_ID_TIME_1
 PARENT_LP_perc_total_TIME_1
 PARENT_NTA_perc_total_TIME_1
 TOTAL_CO_perc_TIME_1
 TOTAL_NC_perc_TIME_1
 VIDEO_ID_TIME_2
 PARENT_LP_perc_total_TIME_2
 PARENT_NTA_perc_total_TIME_2
 TOTAL_CO_perc_TIME_2
 TOTAL_NC_perc_TIME_2
 VIDEO_ID_TIME_3
 PARENT_LP_perc_total_TIME_3
 PARENT_NTA_perc_total_TIME_3
 TOTAL_CO_perc_TIME_3
 TOTAL_NC_perc_TIME_3
 VAR00023
 pre_Qurepack_entered_YN
 pre_Qurepack_entered_INITIALS
 pre_Prev_tx_Qu_entered_YN
 pre_Prev_Tx_Qure_enterd_INITIALS
 pre_EDS_entered_YN
 pre_EDS_entered_INITIALS
 pre_DECA_entered_YN
 pre_DECA_entered_INITIALS
 pre_MCHAT_entered_YN
 pre_MCHAT_entered_INITIALS
 pre_ECBI_entered_YN
 pre_ECBI_entered_INITIALS
 pre_Mullen_entered_YN
 pre_Mullen_entered_INITIALS
 post_Qurepack_entered_YN
 post_Qurepack_entered_INITIALS
 post_DECA_entered_YN
 post_DECA_entered_INITIALS
 post_ECBI_entered_YN
 post_ECBI_entered_INITIALS
 FU_Qurepack_entered_YN
 FU_Qurepack_entered_INITIALS
 FU_DECA_entered_YN
 FU_DECA_entered_INITIALS
 FU_ECBI_entered_YN
 FU_ECBI_entered_INITIALS
 Pre_Ax_1_Date
 Pre_Ax_2_Date
 Pre_Ax_3_Date
 Pre_Home_Visit_Date
 Date_ASD_Ax
 Pre_Qu_Respondent
 Date_Pre_questionnaires
 DOBchild
 SEXchild
 DOBmo
 OCCmo
 OCCmo_category
 EDUmo
 ETHNICITYmo
 DOBfa
 OCCfa
 EDUfa
 ETHNICITYfa
 MARpa
 LANGspoken
 LANGspoken_other
 NUMBHousehold
 INCFamily
 preCBCL1
 preCBCL2
 preCBCL3
 preCBCL4
 preCBCL5
 preCBCL6
 preCBCL7
 preCBCL8
 preCBCL9
 preCBCL10
 preCBCL11
 preCBCL12
 preCBCL13
 preCBCL14
 preCBCL15
 preCBCL16
 preCBCL17
 preCBCL18
 preCBCL19
 preCBCL20
 preCBCL21
 preCBCL22
 preCBCL23
 preCBCL24
 preCBCL25
 preCBCL26
 preCBCL27
 preCBCL28
 preCBCL29
 preCBCL30
 preCBCL31
 preCBCL32
 preCBCL33
 preCBCL34
 preCBCL35
 preCBCL36
 preCBCL37
 preCBCL38
 preCBCL39
 preCBCL40
 preCBCL41
 preCBCL42
 preCBCL43
 preCBCL44
 preCBCL45
 preCBCL46
 preCBCL47
 preCBCL48
 preCBCL49
 preCBCL50
 preCBCL51
 preCBCL52
 preCBCL53
 preCBCL54
 preCBCL55
 preCBCL56
 preCBCL57
 preCBCL58
 preCBCL59
 preCBCL60
 preCBCL61
 preCBCL62
 preCBCL63
 preCBCL64
 preCBCL65
 preCBCL66
 preCBCL67
 preCBCL68
 preCBCL69
 preCBCL70
 preCBCL71
 preCBCL72
 preCBCL73
 preCBCL74
 preCBCL75
 preCBCL76
 preCBCL77
 preCBCL78
 preCBCL79
 preCBCL80
 preCBCL81
 preCBCL82
 preCBCL83
 preCBCL84
 preCBCL85
 preCBCL86
 preCBCL87
 preCBCL88
 preCBCL89
 preCBCL90
 preCBCL91
 preCBCL92
 preCBCL93
 preCBCL94
 preCBCL95
 preCBCL96
 preCBCL97
 preCBCL98
 preCBCL99
 preCBCL100
 preCBCL24A
 preCBCL31A
 preCBCL32A
 preCBCL46A
 preCBCL54A
 preCBCL57A
 preCBCL65A
 preCBCL74A
 preCBCL76A
 preCBCL80A
 preCBCL92A
 preCBCL100A
 prePSI1
 prePSI2
 prePSI3
 prePSI4
 prePSI5
 prePSI6
 prePSI7
 prePSI8
 prePSI9
 prePSI10
 prePSI11
 prePSI12
 prePSI13
 prePSI14
 prePSI15
 prePSI16
 prePSI17
 prePSI18
 prePSI19
 prePSI20
 prePSI21
 prePSI22
 prePSI23
 prePSI24
 prePSI25
 prePSI26
 prePSI27
 prePSI28
 prePSI29
 prePSI30
 prePSI31
 prePSI32
 prePSI33
 prePSI34
 prePSI35
 prePSI36
 preECBQ_Long_A1
 preECBQ_Long_F1
 preECBQ_Long_F2
 preECBQ_Long_F3
 preECBQ_Long_A5
 preECBQ_Long_F4
 preECBQ_Long_F5
 preECBQ_Long_F6
 preECBQ_Long_F7
 preECBQ_Long_F8
 preECBQ_Long_11
 preECBQ_Long_B1
 preECBQ_Long_S1
 preECBQ_Long_S2
 preECBQ_Long_S3
 preECBQ_Long_B5
 preECBQ_Long_S4
 preECBQ_Long_S5
 preECBQ_Long_B8
 preECBQ_Long_B9
 preECBQ_Long_B10
 preECBQ_Long_B11
 preECBQ_Long_B12
 preECBQ_SHORT_F1
 preECBQ_SHORT_F2
 preECBQ_SHORT_F3
 preECBQ_SHORT_F4
 preECBQ_SHORT_F5
 preECBQ_SHORT_F6
 preECBQ_SHORT_F7
 preECBQ_SHORT_F8
 preECBQ_SHORT_S1
 preECBQ_SHORT_S2
 preECBQ_SHORT_S3
 preECBQ_SHORT_S4
 preECBQ_SHORT_S5
 preECRS1
 preECRS2
 preECRS3
 preECRS4
 preECRS5
 preECRS6
 preECRS7
 preECRS8
 preECRS9
 preECRS10
 preECRS11
 preECRS12
 preDERSI1
 preDERSI2
 preDERSI3
 preDERSI4
 preDERSI5
 preDERSI6
 preDERSI7
 preDERSI8
 preDERSI9
 preDERSI10
 preDERSI11
 preDERSI12
 preDERSI13
 preDERSI14
 preDERSI15
 preDERSI16
 preDERSI17
 preDERSI18
 preDERSI19
 preDERSI20
 preDERSI21
 preDERSI22
 preDERSI23
 preDERSI24
 preDERSI25
 preDERSI26
 preDERSI27
 preDERSI28
 preDERSI29
 preDERSI30
 preDERSI31
 preDERSI32
 preDERSI33
 preDERSI34
 preDERSI35
 preDERSI36
 preCCQA1
 preCCQA2
 preCCQA3
 preCCQA4
 preCCQA5
 preCCQA6
 preCCQA7
 preCCQA8
 preCCQA9
 preCCQA10
 preCCQA11
 preCCQA12
 preCCQB1
 preCCQC1
 preCCQC2
 preCCQC3
 preCCQC4
 preCCQC5
 preCCQD1
 preCCQD2
 preCCQD3
 preCCQD4
 preCCQD5
 preCCQD6
 preCCQD7
 preCCQE1
 preCCQE2
 preCCQE3
 preCCQE4
 preCCQE5
 preCCQE6
 preCCQE7
 preCCQE8
 preCCQE9
 preCCQE10
 preCCQE11
 preCCQE12
 preCCQE13
 preCCQE14
 preCCQE15
 preCCQE16
 preCCQE17
 preCCQE18
 preCCQF1
 preCTNES1
 preCTNES2
 preCTNES3
 preCTNES4
 preCTNES5
 preCTNES6
 preCTNES7
 preCTNES8
 preCTNES9
 preCTNES10
 preCTNES11
 preCTNES12
 preBCAP1
 preBCAP2
 preBCAP3
 preBCAP4
 preBCAP5
 preBCAP6
 preBCAP7
 preBCAP8
 preBCAP9
 preBCAP10
 preBCAP11
 preBCAP12
 preBCAP13
 preBCAP14
 preBCAP15
 preBCAP16
 preBCAP17
 preBCAP18
 preBCAP19
 preBCAP20
 preBCAP21
 preBCAP22
 preBCAP23
 preBCAP24
 preBCAP25
 preBCAP26
 preBCAP27
 preBCAP28
 preBCAP29
 preBCAP30
 preBCAP31
 preBCAP32
 preBCAP33
 preBCAP34
 preBITSEA_PF1
 preBITSEA_PF2
 preBITSEA_PF3
 preBITSEA_PF4
 preBITSEA_PF5
 preBITSEA_PF6
 preBITSEA_PF7
 preBITSEA_PF8
 preBITSEA_PF9
 preBITSEA_PF10
 preBITSEA_PF11
 preBITSEA_PF12
 preBITSEA_PF13
 preBITSEA_PF14
 preBITSEA_PF15
 preBITSEA_PF16
 preBITSEA_PF17
 preBITSEA_PF18
 preBITSEA_PF19
 preBITSEA_PF20
 preBITSEA_PF21
 preBITSEA_PF22
 preBITSEA_PF23
 preBITSEA_PF24
 preBITSEA_PF25
 preBITSEA_PF26
 preBITSEA_PF27
 preBITSEA_PF28
 preBITSEA_PF29
 preBITSEA_PF30
 preBITSEA_PF31
 preBITSEA_PF32
 preBITSEA_PF33
 preBITSEA_PF34
 preBITSEA_PF35
 preBITSEA_PF36
 preBITSEA_PF37
 preBITSEA_PF38
 preBITSEA_PF39
 preBITSEA_PF40
 preBITSEA_PF41
 preBITSEA_PF42
 preBITSEA_PFA
 preBITSEA_PFB
 preBITSEA_PF8_details
 preBITSEA_PF36_details
 preBITSEA_PF37_details
 preBITSEA_PF41_details
 preBITSEA_PF42_details
 preECBI_Freq1
 preECBI_Freq2
 preECBI_Freq3
 preECBI_Freq4
 preECBI_Freq5
 preECBI_Freq6
 preECBI_Freq7
 preECBI_Freq8
 preECBI_Freq9
 preECBI_Freq10
 preECBI_Freq11
 preECBI_Freq12
 preECBI_Freq13
 preECBI_Freq14
 preECBI_Freq15
 preECBI_Freq16
 preECBI_Freq17
 preECBI_Freq18
 preECBI_Freq19
 preECBI_Freq20
 preECBI_Freq21
 preECBI_Freq22
 preECBI_Freq23
 preECBI_Freq24
 preECBI_Freq25
 preECBI_Freq26
 preECBI_Freq27
 preECBI_Freq28
 preECBI_Freq29
 preECBI_Freq30
 preECBI_Freq31
 preECBI_Freq32
 preECBI_Freq33
 preECBI_Freq34
 preECBI_Freq35
 preECBI_Freq36
 preECBIP1
 preECBIP2
 preECBIP3
 preECBIP4
 preECBIP5
 preECBIP6
 preECBIP7
 preECBIP8
 preECBIP9
 preECBIP10
 preECBIP11
 preECBIP12
 preECBIP13
 preECBIP14
 preECBIP15
 preECBIP16
 preECBIP17
 preECBIP18
 preECBIP19
 preECBIP20
 preECBIP21
 preECBIP22
 preECBIP23
 preECBIP24
 preECBIP25
 preECBIP26
 preECBIP27
 preECBIP28
 preECBIP29
 preECBIP30
 preECBIP31
 preECBIP32
 preECBIP33
 preECBIP34
 preECBIP35
 preECBIP36
 preEDS1
 preEDS2
 preEDS3
 preEDS4
 preEDS5
 preEDS6
 preEDS7
 preEDS8
 preEDS9
 preEDS10
 preDECA_Inf_1
 preDECA_Inf_2
 preDECA_Inf_3
 preDECA_Inf_4
 preDECA_Inf_5
 preDECA_Inf_6
 preDECA_Inf_7
 preDECA_Inf_8
 preDECA_Inf_9
 preDECA_Inf_10
 preDECA_Inf_11
 preDECA_Inf_12
 preDECA_Inf_13
 preDECA_Inf_14
 preDECA_Inf_15
 preDECA_Inf_16
 preDECA_Inf_17
 preDECA_Inf_18
 preDECA_Inf_19
 preDECA_Inf_20
 preDECA_Inf_21
 preDECA_Inf_22
 preDECA_Inf_23
 preDECA_Inf_24
 preDECA_Inf_25
 preDECA_Inf_26
 preDECA_Inf_27
 preDECA_Inf_28
 preDECA_Inf_29
 preDECA_Inf_30
 preDECA_Inf_31
 preDECA_Inf_32
 preDECA_Inf_33
 preDECA_Tod_1
 preDECA_Tod_2
 preDECA_Tod_3
 preDECA_Tod_4
 preDECA_Tod_5
 preDECA_Tod_6
 preDECA_Tod_7
 preDECA_Tod_8
 preDECA_Tod_9
 preDECA_Tod_10
 preDECA_Tod_11
 preDECA_Tod_12
 preDECA_Tod_13
 preDECA_Tod_14
 preDECA_Tod_15
 preDECA_Tod_16
 preDECA_Tod_17
 preDECA_Tod_18
 preDECA_Tod_19
 preDECA_Tod_20
 preDECA_Tod_21
 preDECA_Tod_22
 preDECA_Tod_23
 preDECA_Tod_24
 preDECA_Tod_25
 preDECA_Tod_26
 preDECA_Tod_27
 preDECA_Tod_28
 preDECA_Tod_29
 preDECA_Tod_30
 preDECA_Tod_31
 preDECA_Tod_32
 preDECA_Tod_33
 preDECA_Tod_34
 preDECA_Tod_35
 preDECA_Tod_36
 prePTQ_COS_NY
 prePTQ_COS_Date
 prePTQ_COS_Length
 prePTQ_PCIT_NY
 prePTQ_PCIT_Date
 prePTQ_PCIT_Length
 prePTQ_TiK_NY
 prePTQ_TiK_Date
 prePTQ_TiK_Length
 prePTQ_PPP_NY
 prePTQ_PPP_Date
 prePTQ_PPP_Length
 prePTQ_PT_NY
 prePTQ_PT_Date
 prePTQ_PT_Length
 prePTQ_Other_NY
 prePTQ_Other_Specify
 prePTQ_Other_Date
 prePTQ_Other_Length
 MCHATR1
 MCHATR2
 MCHATR3
 MCHATR4
 MCHATR5
 MCHATR6
 MCHATR7
 MCHATR8
 MCHATR9
 MCHATR10
 MCHATR11
 MCHATR12
 MCHATR13
 MCHATR14
 MCHATR15
 MCHATR16
 MCHATR17
 MCHATR18
 MCHATR19
 MCHATR20
 MCHATRTotal
 MCHATF1
 MCHATF2
 MCHATF3
 MCHATF4
 MCHATF5
 MCHATF6
 MCHATF7
 MCHATF8
 MCHATF9
 MCHATF10
 MCHATF11
 MCHATF12
 MCHATF13
 MCHATF14
 MCHATF15
 MCHATF16
 MCHATF17
 MCHATF18
 MCHATF19
 MCHATF20
 MCHATFTotal
 MSEL_TimePoint
 MSELGrossMotorRawSCORE
 MSELVIisualReceptionRawSCORE
 MSELFineMotorRawSCORE
 MSELRecptLanguageRawSCORE
 MSELExpressiveLanguageRawSCORE
 MSELGrossMotorTSCORE
 MSELVIisualReceptionTSCORE
 MSELFineMotorTSCORE
 MSELRecptLanguageTSCORE
 MSELExpressiveLanguageTSCORE
 MSELearlylearningcompStandardScr
 pre_ER1
 pre_ER2
 pre_ER3
 pre_ER4
 pre_ER5
 pre_ER6
 pre_ER7
 pre_ER8
 pre_ER9
 pre_ER10
 pre_ER11
 pre_ER12
 pre_ER13
 pre_ER14
 pre_ER15
 pre_ER16
 pre_ER17
 pre_ER18
 pre_ER19
 pre_ER20
 pre_ER21
 pre_ER22
 pre_ER23
 pre_ER24
 pre_ER25
 pre_ER26
 pre_ER27
 pre_ER28
 pre_ER29
 pre_ER30
 pre_ERM1_1_AttDepl
 pre_ERM1_1_SitMod
 pre_ERM1_1_CogCha
 pre_ERM1_1_MatSup
 pre_ERM1_2_AttDeply
 pre_ERM1_2_SitMod
 pre_ERM1_2_CogCha
 pre_ERM1_2_MatSup
 pre_ERM1_3_AttDeply
 pre_ERM1_3_SitMod
 pre_ERM1_3_CogCha
 pre_ERM1_3_MatSup
 pre_ERM1_4_AttDeply
 pre_ERM1_4_SitMod
 pre_ERM1_4_CogCha
 pre_ERM1_4_MatSup
 pre_ERM1_5_AttDeply
 pre_ERM1_5_SitMod
 pre_ERM1_5_CogCha
 pre_ERM1_5_MatSup
 pre_ERM1_6_AttDeply
 pre_ERM1_6_SitMod
 pre_ERM1_6_CogCha
 pre_ERM1_6_MatSup
 pre_ERM2_1_AttDepl
 pre_ERM2_1_SitMod
 pre_ERM2_1_CogCha
 pre_ERM2_1_MatSup
 pre_ERM2_2_AttDepl
 pre_ERM2_2_SitMod
 pre_ERM2_2_CogCha
 pre_ERM2_2_MatSup
 pre_ERM2_3_AttDepl
 pre_ERM2_3_SitMod
 pre_ERM2_3_CogCha
 pre_ERM2_3_MatSup
 pre_ERM2_4_AttDepl
 pre_ERM2_4_SitMod
 pre_ERM2_4_CogCha
 pre_ERM2_4_MatSup
 pre_ERM2_5_AttDepl
 pre_ERM2_5_SitMod
 pre_ERM2_5_CogCha
 pre_ERM2_5_MatSup
 pre_ERM2_6_AttDepl
 pre_ERM2_6_SitMod
 pre_ERM2_6_CogCha
 pre_ERM2_6_MatSup
 pre_ERM3_1_AttDepl
 pre_ERM3_1_SitMod
 pre_ERM3_1_CogCha
 pre_ERM3_1_MatSup
 pre_ERM3_2_AttDepl
 pre_ERM3_2_SitMod
 pre_ERM3_2_CogCha
 pre_ERM3_2_MatSup
 pre_ERM3_3_AttDepl
 pre_ERM3_3_SitMod
 pre_ERM3_3_CogCha
 pre_ERM3_3_MatSup
 pre_ERM3_4_AttDepl
 pre_ERM3_4_SitMod
 pre_ERM3_4_CogCha
 pre_ERM3_4_MatSup
 pre_ERM3_5_AttDepl
 pre_ERM3_5_SitMod
 pre_ERM3_5_CogCha
 pre_ERM3_5_MatSup
 pre_ERM3_6_AttDepl
 pre_ERM3_6_SitMod
 pre_ERM3_6_CogCha
 pre_ERM3_6_MatSup
 pre_ERM4_1_AttDepl
 pre_ERM4_1_SitMod
 pre_ERM4_1_CogCha
 pre_ERM4_1_MatSup
 pre_ERM4_2_AttDepl
 pre_ERM4_2_SitMod
 pre_ERM4_2_CogCha
 pre_ERM4_2_MatSup
 pre_ERM4_3_AttDepl
 pre_ERM4_3_SitMod
 pre_ERM4_3_CogCha
 pre_ERM4_3_MatSup
 pre_ERM4_4_AttDepl
 pre_ERM4_4_SitMod
 pre_ERM4_4_CogCha
 pre_ERM4_4_MatSup
 pre_ERM4_5_AttDepl
 pre_ERM4_5_SitMod
 pre_ERM4_5_CogCha
 pre_ERM4_5_MatSup
 pre_ERM4_6_AttDepl
 pre_ERM4_6_SitMod
 pre_ERM4_6_CogCha
 pre_ERM4_6_MatSup
 pre_ERM5_1_AttDepl
 pre_ERM5_1_SitMod
 pre_ERM5_1_CogCha
 pre_ERM5_1_MatSup
 pre_ERM5_2_AttDepl
 pre_ERM5_2_SitMod
 pre_ERM5_2_CogCha
 pre_ERM5_2_MatSup
 pre_ERM5_3_AttDepl
 pre_ERM5_3_SitMod
 pre_ERM5_3_CogCha
 pre_ERM5_3_MatSup
 pre_ERM5_4_AttDepl
 pre_ERM5_4_SitMod
 pre_ERM5_4_CogCha
 pre_ERM5_4_MatSup
 pre_ERM5_5_AttDepl
 pre_ERM5_5_SitMod
 pre_ERM5_5_CogCha
 pre_ERM5_5_MatSup
 pre_ERM5_6_AttDepl
 pre_ERM5_6_SitMod
 pre_ERM5_6_CogCha
 pre_ERM5_6_MatSup
 pre_MMfreq_Mental
 pre_MMfreq_Behavioural
 pre_MMfreq_Physical
 pre_MMfreq_General
 pre_MMfreq_SelfRef
 ADOST_A1
 ADOST_A1a
 ADOST_A2
 ADOST_A3
 ADOST_A4
 ADOST_A5
 ADOST_A6
 ADOST_A7
 ADOST_A8
 ADOST_A9
 ADOST_A10_Purple
 ADOST_B1_Purple
 ADOST_B2_Purple
 ADOST_B3_Purple
 ADOST_B4_Purple
 ADOST_B5_Purple
 ADOST_B6_Purple
 ADOST_B7_Purple
 ADOST_B8_Purple
 ADOST_B9_Purple
 ADOST_B10_Purple
 ADOST_B11_Purple
 ADOST_B12_Purple
 ADOST_B13_Purple
 ADOST_B14_Purple
 ADOST_B15_Purple
 ADOST_B16a_Purple
 ADOST_B16b_Purple
 ADOST_B17_Purple
 ADOST_B18_Purple
 ADOST_C1_Purple
 ADOST_C2_Purple
 ADOST_C3_Purple
 ADOST_D1_Purple
 ADOST_D2_Purple
 ADOST_D3_Purple
 ADOST_D4_Purple
 ADOST_D5_Purple
 ADOST_E1_Purple
 ADOST_E2_Purple
 ADOST_E3_Purple
 ADOST_E4_Purple
 ADOST_AlgorithmColumn
 ADOST_Purple_SATotal
 ADOST_Purple_RRBTotal
 ADOST_Purple_TotalScore
 ADOST_Yellow_A1
 ADOST_Yellow_A2
 ADOST_Yellow_A3
 ADOST_Yellow_A4
 ADOST_Yellow_A5
 ADOST_Yellow_A6
 ADOST_Yellow_A7
 ADOST_Yellow_B1
 ADOST_Yellow_B2
 ADOST_Yellow_B3
 ADOST_Yellow_B4
 ADOST_Yellow_B5
 ADOST_Yellow_B6
 ADOST_Yellow_B7
 ADOST_Yellow_B8
 ADOST_Yellow_B9a
 ADOST_Yellow_B9b
 ADOST_Yellow_B10
 ADOST_Yellow_B11
 ADOST_Yellow_B12
 ADOST_Yellow_C1
 ADOST_Yellow_C2
 ADOST_Yellow_D1
 ADOST_Yellow_D2
 ADOST_Yellow_D3
 ADOST_Yellow_D4
 ADOST_Yellow_E1
 ADOST_Yellow_E2
 ADOST_Yellow_E3
 ADOST_Yellow_AlgorithmColumn
 ADOST_Yellow_SATotal
 ADOST_Yellow_RRBTotal
 ADOST_Yellow_TotalScore
 Vineland3COMStandardScore
 Vineland3DLSStandardScore
 Vineland3SOCStandardScore
 Vineland3ABCStandardScore
 post_CBCL1
 post_CBCL2
 post_CBCL3
 post_CBCL4
 post_CBCL5
 post_CBCL6
 post_CBCL7
 post_CBCL8
 post_CBCL9
 post_CBCL10
 post_CBCL11
 post_CBCL12
 post_CBCL13
 post_CBCL14
 post_CBCL15
 post_CBCL16
 post_CBCL17
 post_CBCL18
 post_CBCL19
 post_CBCL20
 post_CBCL21
 post_CBCL22
 post_CBCL23
 post_CBCL24
 post_CBCL25
 post_CBCL26
 post_CBCL27
 post_CBCL28
 post_CBCL29
 post_CBCL30
 post_CBCL31
 post_CBCL32
 post_CBCL33
 post_CBCL34
 post_CBCL35
 post_CBCL36
 post_CBCL37
 post_CBCL38
 post_CBCL39
 post_CBCL40
 post_CBCL41
 post_CBCL42
 post_CBCL43
 post_CBCL44
 post_CBCL45
 post_CBCL46
 post_CBCL47
 post_CBCL48
 post_CBCL49
 post_CBCL50
 post_CBCL51
 post_CBCL52
 post_CBCL53
 post_CBCL54
 post_CBCL55
 post_CBCL56
 post_CBCL57
 post_CBCL58
 post_CBCL59
 post_CBCL60
 post_CBCL61
 post_CBCL62
 post_CBCL63
 post_CBCL64
 post_CBCL65
 post_CBCL66
 post_CBCL67
 post_CBCL68
 post_CBCL69
 post_CBCL70
 post_CBCL71
 post_CBCL72
 post_CBCL73
 post_CBCL74
 post_CBCL75
 post_CBCL76
 post_CBCL77
 post_CBCL78
 post_CBCL79
 post_CBCL80
 post_CBCL81
 post_CBCL82
 post_CBCL83
 post_CBCL84
 post_CBCL85
 post_CBCL86
 post_CBCL87
 post_CBCL88
 post_CBCL89
 post_CBCL90
 post_CBCL91
 post_CBCL92
 post_CBCL93
 post_CBCL94
 post_CBCL95
 post_CBCL96
 post_CBCL97
 post_CBCL98
 post_CBCL99
 post_CBCL100
 post_CBCL24A
 post_CBCL31A
 post_CBCL32A
 post_CBCL46A
 post_CBCL54A
 post_CBCL57A
 post_CBCL65A
 post_CBCL74A
 post_CBCL76A
 post_CBCL80A
 post_CBCL92A
 post_CBCL100A
 post_PSI1
 post_PSI2
 post_PSI3
 post_PSI4
 post_PSI5
 post_PSI6
 post_PSI7
 post_PSI8
 post_PSI9
 post_PSI10
 post_PSI11
 post_PSI12
 post_PSI13
 post_PSI14
 post_PSI15
 post_PSI16
 post_PSI17
 post_PSI18
 post_PSI19
 post_PSI20
 post_PSI21
 post_PSI22
 post_PSI23
 post_PSI24
 post_PSI25
 post_PSI26
 post_PSI27
 post_PSI28
 post_PSI29
 post_PSI30
 post_PSI31
 post_PSI32
 post_PSI33
 post_PSI34
 post_PSI35
 post_PSI36
 post_ECBQ_type
 post_ECBQ_LONG_F1_1
 post_ECBQ_LONG_F1_2
 post_ECBQ_LONG_F1_3
 post_ECBQ_LONG_F1_4
 post_ECBQ_LONG_F1_5
 post_ECBQ_LONG_F1_6
 post_ECBQ_LONG_F1_7
 post_ECBQ_LONG_F1_8
 post_ECBQ_LONG_F1_9
 post_ECBQ_LONG_F1_10
 post_ECBQ_LONG_F1_11
 post_ECBQ_LONG_F2_1
 post_ECBQ_LONG_F2_2
 post_ECBQ_LONG_F2_3
 post_ECBQ_LONG_F2_4
 post_ECBQ_LONG_F2_5
 post_ECBQ_LONG_F2_6
 post_ECBQ_LONG_F2_7
 post_ECBQ_LONG_F2_8
 post_ECBQ_LONG_F2_9
 post_ECBQ_LONG_F2_10
 post_ECBQ_LONG_F2_11
 post_ECBQ_LONG_F2_12
 post_ECBQ_SHORT_F1
 post_ECBQ_SHORT_F2
 post_ECBQ_SHORT_F3
 post_ECBQ_SHORT_F4
 post_ECBQ_SHORT_F5
 post_ECBQ_SHORT_F6
 post_ECBQ_SHORT_F7
 post_ECBQ_SHORT_F8
 post_ECBQ_SHORT_S1
 post_ECBQ_SHORT_S2
 post_ECBQ_SHORT_S3
 post_ECBQ_SHORT_S4
 post_ECBQ_SHORT_S5
 post_ECRS1
 post_ECRS2
 post_ECRS3
 post_ECRS4
 post_ECRS5
 post_ECRS6
 post_ECRS7
 post_ECRS8
 post_ECRS9
 post_ECRS10
 post_ECRS11
 post_ECRS12
 post_DERSI1
 post_DERSI2
 post_DERSI3
 post_DERSI4
 post_DERSI5
 post_DERSI6
 post_DERSI7
 post_DERSI8
 post_DERSI9
 post_DERSI10
 post_DERSI11
 post_DERSI12
 post_DERSI13
 post_DERSI14
 post_DERSI15
 post_DERSI16
 post_DERSI17
 post_DERSI18
 post_DERSI19
 post_DERSI20
 post_DERSI21
 post_DERSI22
 post_DERSI23
 post_DERSI24
 post_DERSI25
 post_DERSI26
 post_DERSI27
 post_DERSI28
 post_DERSI29
 post_DERSI30
 post_DERSI31
 post_DERSI32
 post_DERSI33
 post_DERSI34
 post_DERSI35
 post_DERSI36
 post_CCQA1
 post_CCQA2
 post_CCQA3
 post_CCQA4
 post_CCQA5
 post_CCQA6
 post_CCQA7
 post_CCQA8
 post_CCQA9
 post_CCQA10
 post_CCQA11
 post_CCQA12
 post_CCQB1
 post_CCQC1
 post_CCQC2
 post_CCQC3
 post_CCQC4
 post_CCQC5
 post_CCQD1
 post_CCQD2
 post_CCQD3
 post_CCQD4
 post_CCQD5
 post_CCQD6
 post_CCQD7
 post_CCQE1
 post_CCQE2
 post_CCQE3
 post_CCQE4
 post_CCQE5
 post_CCQE6
 post_CCQE7
 post_CCQE8
 post_CCQE9
 post_CCQE10
 post_CCQE11
 post_CCQE12
 post_CCQE13
 post_CCQE14
 post_CCQE15
 post_CCQE16
 post_CCQE17
 post_CCQE18
 post_CCQF1
 post_CTNES1
 post_CTNES2
 post_CTNES3
 post_CTNES4
 post_CTNES5
 post_CTNES6
 post_CTNES7
 post_CTNES8
 post_CTNES9
 post_CTNES10
 post_CTNES11
 post_CTNES12
 post_BCAP1
 post_BCAP2
 post_BCAP3
 post_BCAP4
 post_BCAP5
 post_BCAP6
 post_BCAP7
 post_BCAP8
 post_BCAP9
 post_BCAP10
 post_BCAP11
 post_BCAP12
 post_BCAP13
 post_BCAP14
 post_BCAP15
 post_BCAP16
 post_BCAP17
 post_BCAP18
 post_BCAP19
 post_BCAP20
 post_BCAP21
 post_BCAP22
 post_BCAP23
 post_BCAP24
 post_BCAP25
 post_BCAP26
 post_BCAP27
 post_BCAP28
 post_BCAP29
 post_BCAP30
 post_BCAP31
 post_BCAP32
 post_BCAP33
 post_BCAP34
 post_BITSEA_PF1
 post_BITSEA_PF2
 post_BITSEA_PF3
 post_BITSEA_PF4
 post_BITSEA_PF5
 post_BITSEA_PF6
 post_BITSEA_PF7
 post_BITSEA_PF8
 post_BITSEA_PF8des
 post_BITSEA_PF9
 post_BITSEA_PF10
 post_BITSEA_PF11
 post_BITSEA_PF12
 post_BITSEA_PF13
 post_BITSEA_PF14
 post_BITSEA_PF15
 post_BITSEA_PF16
 post_BITSEA_PF17
 post_BITSEA_PF18
 post_BITSEA_PF19
 post_BITSEA_PF20
 post_BITSEA_PF21
 post_BITSEA_PF22
 post_BITSEA_PF23
 post_BITSEA_PF24
 post_BITSEA_PF25
 post_BITSEA_PF26
 post_BITSEA_PF27
 post_BITSEA_PF28
 post_BITSEA_PF29
 post_BITSEA_PF30
 post_BITSEA_PF31
 post_BITSEA_PF32
 post_BITSEA_PF33
 post_BITSEA_PF34
 post_BITSEA_PF35
 post_BITSEA_PF36
 post_BITSEA_PF36desc
 post_BITSEA_PF37
 post_BITSEA_PF37desc
 post_BITSEA_PF38
 post_BITSEA_PF39
 post_BITSEA_PF40
 post_BITSEA_PF41
 post_BITSEA_PF41desc
 post_BITSEA_PF42
 post_BITSEA_PF42desc
 post_BITSEA_PFA
 post_BITSEA_PFB
 post_ECBI_Freq1
 post_ECBI_Freq2
 post_ECBI_Freq3
 post_ECBI_Freq4
 post_ECBI_Freq5
 post_ECBI_Freq6
 post_ECBI_Freq7
 post_ECBI_Freq8
 post_ECBI_Freq9
 post_ECBI_Freq10
 post_ECBI_Freq11
 post_ECBI_Freq12
 post_ECBI_Freq13
 post_ECBI_Freq14
 post_ECBI_Freq15
 post_ECBI_Freq16
 post_ECBI_Freq17
 post_ECBI_Freq18
 post_ECBI_Freq19
 post_ECBI_Freq20
 post_ECBI_Freq21
 post_ECBI_Freq22
 post_ECBI_Freq23
 post_ECBI_Freq24
 post_ECBI_Freq25
 post_ECBI_Freq26
 post_ECBI_Freq27
 post_ECBI_Freq28
 post_ECBI_Freq29
 post_ECBI_Freq30
 post_ECBI_Freq31
 post_ECBI_Freq32
 post_ECBI_Freq33
 post_ECBI_Freq34
 post_ECBI_Freq35
 post_ECBI_Freq36
 post_ECBIP1
 post_ECBIP2
 post_ECBIP3
 post_ECBIP4
 post_ECBIP5
 post_ECBIP6
 post_ECBIP7
 post_ECBIP8
 post_ECBIP9
 post_ECBIP10
 post_ECBIP11
 post_ECBIP12
 post_ECBIP13
 post_ECBIP14
 post_ECBIP15
 post_ECBIP16
 post_ECBIP17
 post_ECBIP18
 post_ECBIP19
 post_ECBIP20
 post_ECBIP21
 post_ECBIP22
 post_ECBIP23
 post_ECBIP24
 post_ECBIP25
 post_ECBIP26
 post_ECBIP27
 post_ECBIP28
 post_ECBIP29
 post_ECBIP30
 post_ECBIP31
 post_ECBIP32
 post_ECBIP33
 post_ECBIP34
 post_ECBIP35
 post_ECBIP36
 post_EDS1
 post_EDS2
 post_EDS3
 post_EDS4
 post_EDS5
 post_EDS6
 post_EDS7
 post_EDS8
 post_EDS9
 post_EDS10
 post_DECAtype
 post_DECA1
 post_DECA2
 post_DECA3
 post_DECA4
 post_DECA5
 post_DECA6
 post_DECA7
 post_DECA8
 post_DECA9
 post_DECA10
 post_DECA11
 post_DECA12
 post_DECA13
 post_DECA14
 post_DECA15
 post_DECA16
 post_DECA17
 post_DECA18
 post_DECA19
 post_DECA20
 post_DECA21
 post_DECA22
 post_DECA23
 post_DECA24
 post_DECA25
 post_DECA26
 post_DECA27
 post_DECA28
 post_DECA29
 post_DECA30
 post_DECA31
 post_DECA32
 post_DECA33
 post_DECA34
 post_DECA35
 post_DECA36
 post_TAI1
 post_TAI2
 post_TAI3
 post_TAI4
 post_TAI5
 post_TAI6
 post_TAI7
 post_TAI8
 post_TAI9
 post_TAI10
 post_ER1
 post_ER2
 post_ER3
 post_ER4
 post_ER5
 post_ER6
 post_ER7
 post_ER8
 post_ER9
 post_ER10
 post_ER11
 post_ER12
 post_ER13
 post_ER14
 post_ER15
 post_ER16
 post_ER17
 post_ER18
 post_ER19
 post_ER20
 post_ER21
 post_ER22
 post_ER23
 post_ER24
 post_ER25
 post_ER26
 post_ER27
 post_ER28
 post_ER29
 post_ER30
 post_ERM1_1_AttDepl
 post_ERM1_1_SitMod
 post_ERM1_1_CogCha
 post_ERM1_1_MatSup
 post_ERM1_2_AttDepl
 post_ERM1_2_SitMod
 post_ERM1_2_CogCha
 post_ERM1_2_MatSup
 post_ERM1_3_AttDepl
 post_ERM1_3_SitMod
 post_ERM1_3_CogCha
 post_ERM1_3_MatSup
 post_ERM1_4_AttDepl
 post_ERM1_4_SitMod
 post_ERM1_4_CogCha
 post_ERM1_4_MatSup
 post_ERM1_5_AttDepl
 post_ERM1_5_SitMod
 post_ERM1_5_CogCha
 post_ERM1_5_MatSup
 post_ERM1_6AttDep
 post_ERM1_6_SitMod
 post_ERM1_6_CogCha
 post_ERM1_6_MatSup
 post_ERM2_1_AttDepl
 post_ERM2_1_SitMod
 post_ERM2_1_CogCha
 post_ERM2_1_MatSup
 post_ERM2_2_AttDepl
 post_ERM2_2_SitMod
 post_ERM2_2_CogCha
 post_ERM2_2_MatSup
 post_ERM2_3_AttDepl
 post_ERM2_3_SitMod
 post_ERM2_3_CogCha
 post_ERM2_3_MatSup
 post_ERM2_4_AttDepl
 post_ERM2_4_SitMod
 post_ERM2_4_CogCha
 post_ERM2_4_MatSup
 post_ERM2_5_AttDepl
 post_ERM2_5_SitMod
 post_ERM2_5_CogCha
 post_ERM2_5_MatSup
 post_ERM2_6AttDep
 post_ERM2_6_SitMod
 post_ERM2_6_CogCha
 post_ERM2_6_MatSup
 post_ERM3_1_AttDepl
 post_ERM3_1_SitMod
 post_ERM3_1_CogCha
 post_ERM3_1_MatSup
 post_ERM3_2_AttDepl
 post_ERM3_2_SitMod
 post_ERM3_2_CogCha
 post_ERM3_2_MatSup
 post_ERM3_3_AttDepl
 post_ERM3_3_SitMod
 post_ERM3_3_CogCha
 post_ERM3_3_MatSup
 post_ERM3_4_AttDepl
 post_ERM3_4_SitMod
 post_ERM3_4_CogCha
 post_ERM3_4_MatSup
 post_ERM3_5_AttDepl
 post_ERM3_5_SitMod
 post_ERM3_5_CogCha
 post_ERM3_5_MatSup
 post_ERM3_6AttDep
 post_ERM3_6_SitMod
 post_ERM3_6_CogCha
 post_ERM3_6_MatSup
 post_ERM4_1_AttDepl
 post_ERM4_1_SitMod
 post_ERM4_1_CogCha
 post_ERM4_1_MatSup
 post_ERM4_2_AttDepl
 post_ERM4_2_SitMod
 post_ERM4_2_CogCha
 post_ERM4_2_MatSup
 post_ERM4_3_AttDepl
 post_ERM4_3_SitMod
 post_ERM4_3_CogCha
 post_ERM4_3_MatSup
 post_ERM4_4_AttDepl
 post_ERM4_4_SitMod
 post_ERM4_4_CogCha
 post_ERM4_4_MatSup
 post_ERM4_5_AttDepl
 post_ERM4_5_SitMod
 post_ERM4_5_CogCha
 post_ERM4_5_MatSup
 post_ERM4_6AttDep
 post_ERM4_6_SitMod
 post_ERM4_6_CogCha
 post_ERM4_6_MatSup
 post_ERM5_1_AttDepl
 post_ERM5_1_SitMod
 post_ERM5_1_CogCha
 post_ERM5_1_MatSup
 post_ERM5_2_AttDepl
 post_ERM5_2_SitMod
 post_ERM5_2_CogCha
 post_ERM5_2_MatSup
 post_ERM5_3_AttDepl
 post_ERM5_3_SitMod
 post_ERM5_3_CogCha
 post_ERM5_3_MatSup
 post_ERM5_4_AttDepl
 post_ERM5_4_SitMod
 post_ERM5_4_CogCha
 post_ERM5_4_MatSup
 post_ERM5_5_AttDepl
 post_ERM5_5_SitMod
 post_ERM5_5_CogCha
 post_ERM5_5_MatSup
 post_ERM5_6AttDep
 post_ERM5_6_SitMod
 post_ERM5_6_CogCha
 post_ERM5_6_MatSup
 FU_CBCL1
 FU_CBCL2
 FU_CBCL3
 FU_CBCL4
 FU_CBCL5
 FU_CBCL6
 FU_CBCL7
 FU_CBCL8
 FU_CBCL9
 FU_CBCL10
 FU_CBCL11
 FU_CBCL12
 FU_CBCL13
 FU_CBCL14
 FU_CBCL15
 FU_CBCL16
 FU_CBCL17
 FU_CBCL18
 FU_CBCL19
 FU_CBCL20
 FU_CBCL21
 FU_CBCL22
 FU_CBCL23
 FU_CBCL24
 FU_CBCL25
 FU_CBCL26
 FU_CBCL27
 FU_CBCL28
 FU_CBCL29
 FU_CBCL30
 FU_CBCL31
 FU_CBCL32
 FU_CBCL33
 FU_CBCL34
 FU_CBCL35
 FU_CBCL36
 FU_CBCL37
 FU_CBCL38
 FU_CBCL39
 FU_CBCL40
 FU_CBCL41
 FU_CBCL42
 FU_CBCL43
 FU_CBCL44
 FU_CBCL45
 FU_CBCL46
 FU_CBCL47
 FU_CBCL48
 FU_CBCL49
 FU_CBCL50
 FU_CBCL51
 FU_CBCL52
 FU_CBCL53
 FU_CBCL54
 FU_CBCL55
 FU_CBCL56
 FU_CBCL57
 FU_CBCL58
 FU_CBCL59
 FU_CBCL60
 FU_CBCL61
 FU_CBCL62
 FU_CBCL63
 FU_CBCL64
 FU_CBCL65
 FU_CBCL66
 FU_CBCL67
 FU_CBCL68
 FU_CBCL69
 FU_CBCL70
 FU_CBCL71
 FU_CBCL72
 FU_CBCL73
 FU_CBCL74
 FU_CBCL75
 FU_CBCL76
 FU_CBCL77
 FU_CBCL78
 FU_CBCL79
 FU_CBCL80
 FU_CBCL81
 FU_CBCL82
 FU_CBCL83
 FU_CBCL84
 FU_CBCL85
 FU_CBCL86
 FU_CBCL87
 FU_CBCL88
 FU_CBCL89
 FU_CBCL90
 FU_CBCL91
 FU_CBCL92
 FU_CBCL93
 FU_CBCL94
 FU_CBCL95
 FU_CBCL96
 FU_CBCL97
 FU_CBCL98
 FU_CBCL99
 FU_CBCL100
 FU_CBCL24A
 FU_CBCL31A
 FU_CBCL32A
 FU_CBCL46A
 FU_CBCL54A
 FU_CBCL57A
 FU_CBCL65A
 FU_CBCL74A
 FU_CBCL76A
 FU_CBCL80A
 FU_CBCL92A
 FU_CBCL100A
 FU_PSI1
 FU_PSI2
 FU_PSI3
 FU_PSI4
 FU_PSI5
 FU_PSI6
 FU_PSI7
 FU_PSI8
 FU_PSI9
 FU_PSI10
 FU_PSI11
 FU_PSI12
 FU_PSI13
 FU_PSI14
 FU_PSI15
 FU_PSI16
 FU_PSI17
 FU_PSI18
 FU_PSI19
 FU_PSI20
 FU_PSI21
 FU_PSI22
 FU_PSI23
 FU_PSI24
 FU_PSI25
 FU_PSI26
 FU_PSI27
 FU_PSI28
 FU_PSI29
 FU_PSI30
 FU_PSI31
 FU_PSI32
 FU_PSI33
 FU_PSI34
 FU_PSI35
 FU_PSI36
 FU_ECBQ_type
 FU_ECBQ_LONG_F1_1
 FU_ECBQ_LONG_F1_2
 FU_ECBQ_LONG_F1_3
 FU2_ECBQ_LONG_F1_4
 FU_ECBQ_LONG_F1_5
 FU_ECBQ_LONG_F1_6
 FU_ECBQ_LONG_F1_7
 FU_ECBQ_LONG_F1_8
 FU_ECBQ_LONG_F1_9
 FU_ECBQ_LONG_F1_10
 FU_ECBQ_LONG_F1_11
 FU_ECBQ_LONG_F2_1
 FU_ECBQ_LONG_F2_2
 FU_ECBQ_LONG_F2_3
 FU_ECBQ_LONG_F2_4
 FU_ECBQ_LONG_F2_5
 FU_ECBQ_LONG_F2_6
 FU_ECBQ_LONG_F2_7
 FU_ECBQ_LONG_F2_8
 FU_ECBQ_LONG_F2_9
 FU_ECBQ_LONG_F2_10
 FU_ECBQ_LONG_F2_11
 FU_ECBQ_LONG_F2_12
 FU_ECBQ_SHORT_F1
 FU_ECBQ_SHORT_F2
 FU_ECBQ_SHORT_F3
 FU_ECBQ_SHORT_F4
 FU_ECBQ_SHORT_F5
 FU_ECBQ_SHORT_F6
 FU_ECBQ_SHORT_F7
 FU_ECBQ_SHORT_F8
 FU_ECBQ_SHORT_S1
 FU_ECBQ_SHORT_S2
 FU_ECBQ_SHORT_S3
 FU_ECBQ_SHORT_S4
 FU_ECBQ_SHORT_S5
 FU_ECRS1
 FU_ECRS2
 FU_ECRS3
 FU_ECRS4
 FU_ECRS5
 FU_ECRS6
 FU_ECRS7
 FU_ECRS8
 FU_ECRS9
 FU_ECRS10
 FU_ECRS11
 FU_ECRS12
 FU_DERSI1
 FU_DERSI2
 FU_DERSI3
 FU_DERSI4
 FU_DERSI5
 FU_DERSI6
 FU_DERSI7
 FU_DERSI8
 FU_DERSI9
 FU_DERSI10
 FU_DERSI11
 FU_DERSI12
 FU_DERSI13
 FU_DERSI14
 FU_DERSI15
 FU_DERSI16
 FU_DERSI17
 FU_DERSI18
 FU_DERSI19
 FU_DERSI20
 FU_DERSI21
 FU_DERSI22
 FU_DERSI23
 FU_DERSI24
 FU_DERSI25
 FU_DERSI26
 FU_DERSI27
 FU_DERSI28
 FU_DERSI29
 FU_DERSI30
 FU_DERSI31
 FU_DERSI32
 FU_DERSI33
 FU_DERSI34
 FU_DERSI35
 FU_DERSI36
 FU_CCQA1
 FU_CCQA2
 FU_CCQA3
 FU_CCQA4
 FU_CCQA5
 FU_CCQA6
 FU_CCQA7
 FU_CCQA8
 FU_CCQA9
 FU_CCQA10
 FU_CCQA11
 FU_CCQA12
 FU_CCQB1
 FU_CCQC1
 FU_CCQC2
 FU_CCQC3
 FU_CCQC4
 FU_CCQC5
 FU_CCQD1
 FU_CCQD2
 FU_CCQD3
 FU_CCQD4
 FU_CCQD5
 FU_CCQD6
 FU_CCQD7
 FU_CCQE1
 FU_CCQE2
 FU_CCQE3
 FU_CCQE4
 FU_CCQE5
 FU_CCQE6
 FU_CCQE7
 FU_CCQE8
 FU_CCQE9
 FU_CCQE10
 FU_CCQE11
 FU_CCQE12
 FU_CCQE13
 FU_CCQE14
 FU_CCQE15
 FU_CCQE16
 FU_CCQE17
 FU_CCQE18
 FU_CCQF1
 FU_CTNES1
 FU_CTNES2
 FU_CTNES3
 FU_CTNES4
 FU_CTNES5
 FU_CTNES6
 FU_CTNES7
 FU_CTNES8
 FU_CTNES9
 FU_CTNES10
 FU_CTNES11
 FU_CTNES12
 FU_BCAP1
 FU_BCAP2
 FU_BCAP3
 FU_BCAP4
 FU_BCAP5
 FU_BCAP6
 FU_BCAP7
 FU_BCAP8
 FU_BCAP9
 FU_BCAP10
 FU_BCAP11
 FU_BCAP12
 FU_BCAP13
 FU_BCAP14
 FU_BCAP15
 FU_BCAP16
 FU_BCAP17
 FU_BCAP18
 FU_BCAP19
 FU_BCAP20
 FU_BCAP21
 FU_BCAP22
 FU_BCAP23
 FU_BCAP24
 FU_BCAP25
 FU_BCAP26
 FU_BCAP27
 FU_BCAP28
 FU_BCAP29
 FU_BCAP30
 FU_BCAP31
 FU_BCAP32
 FU_BCAP33
 FU_BCAP34
 FU_BITSEA_PF1
 FU_BITSEA_PF2
 FU_BITSEA_PF3
 FU_BITSEA_PF4
 FU_BITSEA_PF5
 FU_BITSEA_PF6
 FU_BITSEA_PF7
 FU_BITSEA_PF8
 FU_BITSEA_PF9
 FU_BITSEA_PF10
 FU_BITSEA_PF11
 FU_BITSEA_PF12
 FU_BITSEA_PF13
 FU_BITSEA_PF14
 FU_BITSEA_PF15
 FU_BITSEA_PF16
 FU_BITSEA_PF17
 FU_BITSEA_PF18
 FU_BITSEA_PF19
 FU_BITSEA_PF20
 FU_BITSEA_PF21
 FU_BITSEA_PF22
 FU_BITSEA_PF23
 FU_BITSEA_PF24
 FU_BITSEA_PF25
 FU_BITSEA_PF26
 FU_BITSEA_PF27
 FU_BITSEA_PF28
 FU_BITSEA_PF29
 FU_BITSEA_PF30
 FU_BITSEA_PF31
 FU_BITSEA_PF32
 FU_BITSEA_PF33
 FU_BITSEA_PF34
 FU_BITSEA_PF35
 FU_BITSEA_PF36
 FU_BITSEA_PF37
 FU_BITSEA_PF38
 FU_BITSEA_PF39
 FU_BITSEA_PF40
 FU_BITSEA_PF41
 FU_BITSEA_PF42
 FU_BITSEA_PFA
 FU_BITSEA_PFB
 FU_ECBI_Freq1
 FU_ECBI_Freq2
 FU_ECBI_Freq3
 FU_ECB_Freq4
 FU_ECBI_Freq5
 FU_ECBI_Freq6
 FU_ECBI_Freq7
 FU_ECBI_Freq8
 FU_ECBI_Freq9
 FU_ECBI_Freq10
 FU_ECBI_Freq11
 FU_ECBI_Freq12
 FU_ECBI_Freq13
 FU_ECBI_Freq14
 FU_ECBI_Freq15
 FU_ECBI_Freq16
 FU_ECBI_Freq17
 FU_ECBI_Freq18
 FU_ECBI_Freq19
 FU_ECBI_Freq20
 FU_ECBI_Freq21
 FU_ECBI_Freq22
 FU_ECBI_Freq23
 FU_ECBI_Freq24
 FU_ECBI_Freq25
 FU_ECBI_Freq26
 FU_ECBI_Freq27
 FU_ECBI_Freq28
 FU_ECBI_Freq29
 FU_ECBI_Freq30
 FU_ECBI_Freq31
 FU_ECBI_Freq32
 FU_ECBI_Freq33
 FU_ECBI_Freq34
 FU_ECBI_Freq35
 FU_ECBI_Freq36
 FU_ECBIP1
 FU_ECBIP2
 FU_ECBIP3
 FU_ECBIP4
 FU_ECBIP5
 FU_ECBIP6
 FU_ECBIP7
 FU_ECBIP8
 FU_ECBIP9
 FU_ECBIP10
 FU_ECBIP11
 FU_ECBIP12
 FU_ECBIP13
 FU_ECBIP14
 FU_ECBIP15
 FU_ECBIP16
 FU_ECBIP17
 FU_ECBIP18
 FU_ECBIP19
 FU_ECBIP20
 FU_ECBIP21
 FU_ECBIP22
 FU_ECBIP23
 FU_ECBIP24
 FU_ECBIP25
 FU_ECBIP26
 FU_ECBIP27
 FU_ECBIP28
 FU_ECBIP29
 FU_ECBIP30
 FU_ECBIP31
 FU_ECBIP32
 FU_ECBIP33
 FU_ECBIP34
 FU_ECBIP35
 FU_ECBIP36
 FU_EDS1
 FU_EDS2
 FU_EDS3
 FU_EDS4
 FU_EDS5
 FU_EDS6
 FU_EDS7
 FU_EDS8
 FU_EDS9
 FU_EDS10
 FU_DECAtype
 FU_DECA1
 FU_DECA2
 FU_DECA3
 FU_DECA4
 FU_DECA5
 FU_DECA6
 FU_DECA7
 FU_DECA8
 FU_DECA9
 FU_DECA10
 FU_DECA11
 FU_DECA12
 FU_DECA13
 FU_DECA14
 FU_DECA15
 FU_DECA16
 FU_DECA17
 FU_DECA18
 FU_DECA19
 FU_DECA20
 FU_DECA21
 FU_DECA22
 FU_DECA23
 FU_DECA24
 FU_DECA25
 FU_DECA26
 FU_DECA27
 FU_DECA28
 FU_DECA29
 FU_DECA30
 FU_DECA31
 FU_DECA32
 FU_DECA33
 FU_DECA34
 FU_DECA35
 FU_DECA36
 FU_ER1
 FU_ER2
 FU_ER3
 FU_ER4
 FU_ER5
 FU_ER6
 FU_ER7
 FU_ER8
 FU_ER9
 FU_ER10
 FU_ER11
 FU_ER12
 FU_ER13
 FU_ER14
 FU_ER15
 FU_ER16
 FU_ER17
 FU_ER18
 FU_ER19
 FU_ER20
 FU_ER21
 FU_ER22
 FU_ER23
 FU_ER24
 FU_ER25
 FU_ER26
 FU_ER27
 FU_ER28
 FU_ER29
 FU_ER30
 FU_ERM1_1_AttDepl
 FU_ERM1_1_SitMod
 FU_ERM1_1_CogCha
 FU_ERM1_1_MatSup
 FU_ERM1_2_AttDepl
 FU_ERM1_2_SitMod
 FU_ERM1_2_CogCha
 FU_ERM1_2_MatSup
 FU_ERM1_3_AttDepl
 FU_ERM1_3_SitMod
 FU_ERM1_3_CogCha
 FU_ERM1_3_MatSup
 FU_ERM1_4_AttDepl
 FU_ERM1_4_SitMod
 FU_ERM1_4_CogCha
 FU_ERM1_4_MatSup
 FU_ERM1_5_AttDepl
 FU_ERM1_5_SitMod
 FU_ERM1_5_CogCha
 FU_ERM1_5_MatSup
 FU_ERM1_6_AttDepl
 FU_ERM1_6_SitMod
 FU_ERM1_6_CogCha
 FU_ERM1_6_MatSup
 FU_ERM2_1_AttDepl
 FU_ERM2_1_SitMod
 FU_ERM2_1_CogCha
 FU_ERM2_1_MatSup
 FU_ERM2_2_AttDepl
 FU_ERM2_2_SitMod
 FU_ERM2_2_CogCha
 FU_ERM2_2_MatSup
 FU_ERM2_3_AttDepl
 FU_ERM2_3_SitMod
 FU_ERM2_3_CogCha
 FU_ERM2_3_MatSup
 FU_ERM2_4_AttDepl
 FU_ERM2_4_SitMod
 FU_ERM2_4_CogCha
 FU_ERM2_4_MatSup
 FU_ERM2_5_AttDepl
 FU_ERM2_5_SitMod
 FU_ERM2_5_CogCha
 FU_ERM2_5_MatSup
 FU_ERM2_6_AttDepl
 FU_ERM2_6_SitMod
 FU_ERM2_6_CogCha
 FU_ERM2_6_MatSup
 FU_ERM3_1_AttDepl
 FU_ERM3_1_SitMod
 FU_ERM3_1_CogCha
 FU_ERM3_1_MatSup
 FU_ERM3_2_AttDepl
 FU_ERM3_2_SitMod
 FU_ERM3_2_CogCha
 FU_ERM3_2_MatSup
 FU_ERM3_3_AttDepl
 FU_ERM3_3_SitMod
 FU_ERM3_3_CogCha
 FU_ERM3_3_MatSup
 FU_ERM3_4_AttDepl
 FU_ERM3_4_SitMod
 FU_ERM3_4_CogCha
 FU_ERM3_4_MatSup
 FU_ERM3_5_AttDepl
 FU_ERM3_5_SitMod
 FU_ERM3_5_CogCha
 FU_ERM3_5_MatSup
 FU_ERM3_6_AttDepl
 FU_ERM3_6_SitMod
 FU_ERM3_6_CogCha
 FU_ERM3_6_MatSup
 FU_ERM4_1_AttDepl
 FU_ERM4_1_SitMod
 FU_ERM4_1_CogCha
 FU_ERM4_1_MatSup
 FU_ERM4_2_AttDepl
 FU_ERM4_2_SitMod
 FU_ERM4_2_CogCha
 FU_ERM4_2_MatSup
 FU_ERM4_3_AttDepl
 FU_ERM4_3_SitMod
 FU_ERM4_3_CogCha
 FU_ERM4_3_MatSup
 FU_ERM4_4_AttDepl
 FU_ERM4_4_SitMod
 FU_ERM4_4_CogCha
 FU_ERM4_4_MatSup
 FU_ERM4_5_AttDepl
 FU_ERM4_5_SitMod
 FU_ERM4_5_CogCha
 FU_ERM4_5_MatSup
 FU_ERM4_6_AttDepl
 FU_ERM4_6_SitMod
 FU_ERM4_6_CogCha
 FU_ERM4_6_MatSup
 FU_ERM5_1_AttDepl
 FU_ERM5_1_SitMod
 FU_ERM5_1_CogCha
 FU_ERM5_1_MatSup
 FU_ERM5_2_AttDepl
 FU_ERM5_2_SitMod
 FU_ERM5_2_CogCha
 FU_ERM5_2_MatSup
 FU_ERM5_3_AttDepl
 FU_ERM5_3_SitMod
 FU_ERM5_3_CogCha
 FU_ERM5_3_MatSup
 FU_ERM5_4_AttDepl
 FU_ERM5_4_SitMod
 FU_ERM5_4_CogCha
 FU_ERM5_4_MatSup
 FU_ERM5_5_AttDepl
 FU_ERM5_5_SitMod
 FU_ERM5_5_CogCha
 FU_ERM5_5_MatSup
 FU_ERM5_6_AttDepl
 FU_ERM5_6_SitMod
 FU_ERM5_6_CogCha
 FU_ERM5_6_MatSup
 FU_PTQ_COS_NY
 FU_PTQ_COS_Date
 FU_PTQ_COS_Length
 FU_PTQ_PCIT_NY
 FU_PTQ_PCIT_Date
 FU_PTQ_PCIT_Length
 FU_PTQ_TiK_NY
 FU_PTQ_TiK_Date
 FU_PTQ_TiK_Length
 FU_PTQ_PPP_NY
 FU_PTQ_PPP_Date
 FU_PTQ_PPP_Length
 FU_PTQ_PT_NY
 FU_PTQ_PT_Date
 FU_PTQ_PT_Length
 FU_PTQ_Other_NY
 FU_PTQ_Other_Specify
 FU_PTQ_Other_Date
 FU_PTQ_Other_Length
 Baseline_sensitivity_Coder
 NICHD_Sit1_Sensitivity_Distress
 NICHD_Sit1_Sensitivity_NonDstrss
 NICHD_Sit1_Intrusiveness
 NICHD_Sit1_Detachment
 NICHD_Sit1_Positive_Regard
 NICHD_Sit1_Negative_Regard
 NICHD_Sit1_child_Positive_Mood
 NICHD_Sit1_child_Negative_Mood
 NICHD_Sit1_child_Sociability
 NICHD_Sit1_child_Attention
 NICHD_Sit2_Sensitivity_Distress
 NICHD_Sit2_Sensitivity_NonDstrss
 NICHD_Sit2_Intrusiveness
 NICHD_Sit2_Detachment
 NICHD_Sit2_Positive_Regard
 NICHD_Sit2_Negative_Regard
 NICHD_Sit2_child_Positive_Mood
 NICHD_Sit2_child_Negative_Mood
 NICHD_Sit2_child_Sociability
 NICHD_Sit2_child_Attention
 NICHD_Sit3_Sensitivity_Distress
 NICHD_Sit3_Sensitivity_NonDstrss
 NICHD_Sit3_Intrusiveness
 NICHD_Sit3_Detachment
 NICHD_Sit3_Positive_Regard
 NICHD_Sit3_Negative_Regard
 NICHD_Sit3_child_Positive_Mood
 NICHD_Sit3_child_Negative_Mood
 NICHD_Sit3_child_Sociability
 NICHD_Sit3_child_Attention
 NICHD_Sit4_Sensitivity_Distress
 NICHD_Sit4_Sensitivity_NonDstrss
 NICHD_Sit4_Intrusiveness
 NICHD_Sit4_Detachment
 NICHD_Sit4_Positive_Regard
 NICHD_Sit4_Negative_Regard
 NICHD_Sit4_child_Positive_Mood
 NICHD_Sit4_child_Negative_Mood
 NICHD_Sit4_child_Sociability
 NICHD_Sit4_child_Attention
 NICHD_Sit5_Sensitivity_Distress
 NICHD_Sit5_Sensitivity_NonDstrss
 NICHD_Sit5_Intrusiveness
 NICHD_Sit5_Detachment
 NICHD_Sit5_Positive_Regard
 NICHD_Sit5_Negative_Regard
 NICHD_Sit5_child_Positive_Mood
 NICHD_Sit5_child_Negative_Mood
 NICHD_Sit5_child_Sociability
 NICHD_Sit5_child_Attention
 NICHD_post_Sit1_Sensitvty_Dstrss
 NICHD_post_Sit1_Snstvty_NnDstrss
 NICHD_post_Sit1_Intrusiveness
 NICHD_post_Sit1_Detachment
 NICHD_post_Sit1_Positive_Regard
 NICHD_post_Sit1_Negative_Regard
 NICHD_post_Sit1_child_Positiv_Md
 NICHD_post_Sit1_child_Negativ_Md
 NICHD_post_Sit1_child_Sociabilty
 NICHD_post_Sit1_child_Attention
 NICHD_post_Sit2_Sensitvty_Dstrss
 NICHD_post_Sit2_Snstvty_NnDstrss
 NICHD_post_Sit2_Intrusiveness
 NICHD_post_Sit2_Detachment
 NICHD_post_Sit2_Positive_Regard
 NICHD_post_Sit2_Negative_Regard
 NICHD_post_Sit2_child_Positiv_Md
 NICHD_post_Sit2_child_Negativ_Md
 NICHD_post_Sit2_child_Sociabilty
 NICHD_post_Sit2_child_Attention
 NICHD_post_Sit3_Sensitvty_Dstrss
 NICHD_post_Sit3_Snstvty_NnDstrss
 NICHD_post_Sit3_Intrusiveness
 NICHD_post_Sit3_Detachment
 NICHD_post_Sit3_Positive_Regard
 NICHD_post_Sit3_Negative_Regard
 NICHD_post_Sit3_child_Positiv_Md
 NICHD_post_Sit3_child_Negativ_Md
 NICHD_post_Sit3_child_Sociabilty
 NICHD_post_Sit3_child_Attention
 NICHD_post_Sit4_Sensitvty_Dstrss
 NICHD_post_Sit4_Snstvty_NnDstrss
 NICHD_post_Sit4_Intrusiveness
 NICHD_post_Sit4_Detachment
 NICHD_post_Sit4_Positive_Regard
 NICHD_post_Sit4_Negative_Regard
 NICHD_post_Sit4_child_Positiv_Md
 NICHD_post_Sit4_child_Negativ_Md
 NICHD_post_Sit4_child_Sociabilty
 NICHD_post_Sit4_child_Attention
 NICHD_post_Sit5_Sensitvty_Dstrss
 NICHD_post_Sit5_Snstvty_NnDstrss
 NICHD_post_Sit5_Intrusiveness
 NICHD_post_Sit5_Detachment
 NICHD_post_Sit5_Positive_Regard
 NICHD_post_Sit5_Negative_Regard
 NICHD_post_Sit5_child_Positiv_Md
 NICHD_post_Sit5_child_Negativ_Md
 NICHD_post_Sit5_child_Sociabilty
 NICHD_post_Sit5_child_Attention
 NICHD_FU_Sit1_Sensitivity_Dstrss
 NICHD_FU_Sit1_Sensitvty_NnDstrss
 NICHD_FU_Sit1_Intrusiveness
 NICHD_FU_Sit1_Detachment
 NICHD_FU_Sit1_Positive_Regard
 NICHD_FU_Sit1_Negative_Regard
 NICHD_FU_Sit1_child_Positive_Mod
 NICHD_FU_Sit1_child_Negative_Mod
 NICHD_FU_Sit1_child_Sociability
 NICHD_FU_Sit1_child_Attention
 NICHD_FU_Sit2_Sensitivity_Dstrss
 NICHD_FU_Sit2_Sensitvty_NnDstrss
 NICHD_FU_Sit2_Intrusiveness
 NICHD_FU_Sit2_Detachment
 NICHD_FU_Sit2_Positive_Regard
 NICHD_FU_Sit2_Negative_Regard
 NICHD_FU_Sit2_child_Positive_Mod
 NICHD_FU_Sit2_child_Negative_Mod
 NICHD_FU_Sit2_child_Sociability
 NICHD_FU_Sit2_child_Attention
 NICHD_FU_Sit3_Sensitivity_Dstrss
 NICHD_FU_Sit3_Sensitvty_NnDstrss
 NICHD_FU_Sit3_Intrusiveness
 NICHD_FU_Sit3_Detachment
 NICHD_FU_Sit3_Positive_Regard
 NICHD_FU_Sit3_Negative_Regard
 NICHD_FU_Sit3_child_Positive_Mod
 NICHD_FU_Sit3_child_Negative_Mod
 NICHD_FU_Sit3_child_Sociability
 NICHD_FU_Sit3_child_Attention
 NICHD_FU_Sit4_Sensitivity_Dstrss
 NICHD_FU_Sit4_Sensitvty_NnDstrss
 NICHD_FU_Sit4_Intrusiveness
 NICHD_FU_Sit4_Detachment
 NICHD_FU_Sit4_Positive_Regard
 NICHD_FU_Sit4_Negative_Regard
 NICHD_FU_Sit4_child_Positive_Mod
 NICHD_FU_Sit4_child_Negative_Mod
 NICHD_FU_Sit4_child_Sociability
 NICHD_FU_Sit4_child_Attention
 NICHD_FU_Sit5_Sensitivity_Dstrss
 NICHD_FU_Sit5_Sensitvty_NnDstrss
 NICHD_FU_Sit5_Intrusiveness
 NICHD_FU_Sit5_Detachment
 NICHD_FU_Sit5_Positive_Regard
 NICHD_FU_Sit5_Negative_Regard
 NICHD_FU_Sit5_child_Positive_Mod
 NICHD_FU_Sit5_child_Negative_Mod
 NICHD_FU_Sit5_child_Sociability
 NICHD_FU_Sit5_child_Attention
 SSP_Pre_Code_betty_gave
 SSP_Pre_three_way_classification
 SSP_Pre_three_way_secure_or_nscr
 SSP_Pre_four_way_classification
 SSP_Pre_four_way_rgnzd_r_dsrgnzd
 SSP_Post__Code_betty_gave
 SSP_Post__three_way_classificatn
 SSP_Post_three_way_secure_r_nscr
 SSP_Post__four_way_classificatin
 SSP_Post_four_wy_rgnzd_r_dsrgnzd
 VAR00001
 VAR00002
 VAR00003
 VAR00004
 VAR00005
 VAR00006
 VAR00007
 NICHD_Sensitivity_to_distrss_ttl
 NICHD_Sensitivity_nondistrss_ttl
 NICHD_Intrusive_total
 NICHD_Detachment_total
 NICHD_Positive_total
 NICHD_Negative_total
 NICHD_Child_Positive_total
 NICHD_Child_Negative_total
 NICHD_Child_sociability_total
 NICHD_Child_attention_total
 NICHD_Intrusive_total_REVERSED
 NICHD_Detachment_total_REVERSED
 NICHD_mother_negatv_ttl_REVERSED
 NICHD_Child_Negativ_ttl_REVERSED
 NICHD_total_sensitivity
 post_NICHD_Senstvty_t_dstrss_ttl
 post_NICHD_Senstvty_nndstrss_ttl
 post_NICHD_Intrusive_total
 post_NICHD_Detachment_total
 post_NICHD_Positive_total
 post_NICHD_Negative_total
 post_NICHD_Child_Positive_total
 post_NICHD_Child_Negative_total
 post_NICHD_Child_sociability_ttl
 post_NICHD_Child_attention_total
 post_NICHD_Intrusiv_ttl_REVERSED
 post_NICHD_Detchmnt_ttl_REVERSED
 pst_NICHD_mthr_ngtv_ttl_REVERSED
 pst_NICHD_Chld_Ngtv_ttl_REVERSED
 post_NICHD_total_sensitivity
 FU_NICHD_Sensitivty_t_dstrss_ttl
 FU_NICHD_Sensitivty_nndstrss_ttl
 FU_NICHD_Intrusive_total
 FU_NICHD_Detachment_total
 FU_NICHD_Positive_total
 FU_NICHD_Negative_total
 FU_NICHD_Child_Positive_total
 FU_NICHD_Child_Negative_total
 FU_NICHD_Child_sociability_total
 FU_NICHD_Child_attention_total
 FU_NICHD_Intrusive_totl_REVERSED
 FU_NICHD_Detachment_ttl_REVERSED
 FU_NICHD_mothr_ngtv_ttl_REVERSED
 FU_NICHD_Child_Ngtv_ttl_REVERSED
 FU_NICHD_total_sensitivity
 preBCAP1_recoded
 preBCAP2_recoded
 preBCAP3_recoded
 preBCAP4_recoded
 preBCAP5_recoded
 preBCAP6_recoded
 preBCAP7_recoded
 preBCAP8_recoded
 preBCAP9_recoded
 preBCAP10_recoded
 preBCAP11_recoded
 preBCAP12_recoded
 preBCAP13_recoded
 preBCAP14_recoded
 preBCAP15_recoded
 preBCAP16_recoded
 preBCAP17_recoded
 preBCAP18_recoded
 preBCAP19_recoded
 preBCAP20_recoded
 preBCAP21_recoded
 preBCAP22_recoded
 preBCAP23_recoded
 preBCAP24_recoded
 preBCAP25_recoded
 preBCAP26_recoded
 preBCAP27_recoded
 preBCAP28_recoded
 preBCAP29_recoded
 preBCAP30_recoded
 preBCAP31_recoded
 preBCAP32_recoded
 preBCAP33_recoded
 preBCAP34_recoded
 preBCAP2_recoded_REVERSED
 preBCAP1_recoded_REVERSED
 preBCAP29_recoded_REVERSED
 preBCAP23_recoded_REVERSED
 preBCAP_RANDOM_RESPONDING
 preBCAP_LIE
 preBCAP_risk
 post_BCAP1_recoded
 post_BCAP2_recoded
 post_BCAP3_recoded
 post_BCAP4_recoded
 post_BCAP5_recoded
 post_BCAP6_recoded
 post_BCAP7_recoded
 post_BCAP8_recoded
 post_BCAP9_recoded
 post_BCAP10_recoded
 post_BCAP11_recoded
 post_BCAP12_recoded
 post_BCAP13_recoded
 post_BCAP14_recoded
 post_BCAP15_recoded
 post_BCAP16_recoded
 post_BCAP17_recoded
 post_BCAP18_recoded
 post_BCAP19_recoded
 post_BCAP20_recoded
 post_BCAP21_recoded
 post_BCAP22_recoded
 post_BCAP23_recoded
 post_BCAP24_recoded
 post_BCAP25_recoded
 post_BCAP26_recoded
 post_BCAP27_recoded
 post_BCAP28_recoded
 post_BCAP29_recoded
 post_BCAP30_recoded
 post_BCAP31_recoded
 post_BCAP32_recoded
 post_BCAP33_recoded
 post_BCAP34_recoded
 post_BCAP2_recoded_REVERSED
 post_BCAP1_recoded_REVERSED
 post_BCAP29_recoded_REVERSED
 post_BCAP23_recoded_REVERSED
 post_BCAP_RANDOM_RESPONDING
 post_BCAP_LIE
 post_BCAP_risk
 FU_BCAP1_recoded
 FU_BCAP2_recoded
 FU_BCAP3_recoded
 FU_BCAP4_recoded
 FU_BCAP5_recoded
 FU_BCAP6_recoded
 FU_BCAP7_recoded
 FU_BCAP8_recoded
 FU_BCAP9_recoded
 FU_BCAP10_recoded
 FU_BCAP11_recoded
 FU_BCAP12_recoded
 FU_BCAP13_recoded
 FU_BCAP14_recoded
 FU_BCAP15_recoded
 FU_BCAP16_recoded
 FU_BCAP17_recoded
 FU_BCAP18_recoded
 FU_BCAP19_recoded
 FU_BCAP20_recoded
 FU_BCAP21_recoded
 FU_BCAP22_recoded
 FU_BCAP23_recoded
 FU_BCAP24_recoded
 FU_BCAP25_recoded
 FU_BCAP26_recoded
 FU_BCAP27_recoded
 FU_BCAP28_recoded
 FU_BCAP29_recoded
 FU_BCAP30_recoded
 FU_BCAP31_recoded
 FU_BCAP32_recoded
 FU_BCAP33_recoded
 FU_BCAP34_recoded
 FU_BCAP2_recoded_REVERSED
 FU_BCAP1_recoded_REVERSED
 FU_BCAP29_recoded_REVERSED
 FU_BCAP23_recoded_REVERSED
 FU_BCAP_RANDOM_RESPONDING
 FU_BCAP_LIE
 FU_BCAP_risk
 preCCQA12_R
 post_CCQA12_R
 FU_CCQA12_R
 pre_CCQ_A_TOPSE
 post_CCQ_A_TOPSE
 FU_CCQ_A_TOPSE
 pre_CCQ_C_LSAC_H
 post_CCQ_C_LSAC_H
 FU_CCQ_C_LSAC_H
 preCCQE4_R
 preCCQE9_R
 preCCQE14_R
 post_CCQE4_R
 post_CCQE9_R
 post_CCQE14_R
 FU_CCQE4_R
 FU_CCQE9_R
 FU_CCQE14_R
 pre_CCQ_E_Ref_Fun
 post_CCQ_E_Ref_Fun
 FU_CCQ_E_Ref_Fun
 Child_Age
;
LABEL  pre_Prev_Tx_Qure_enterd_INITIALS = "pre_Prev_Tx_Qure_entered_INITIALS" ;
LABEL  MSELearlylearningcompStandardScr = "MSELearlylearningcompStandardScore" ;
LABEL  NICHD_Sit1_Sensitivity_NonDstrss = "NICHD_Sit1_Sensitivity_NonDistress" ;
LABEL  NICHD_Sit2_Sensitivity_NonDstrss = "NICHD_Sit2_Sensitivity_NonDistress" ;
LABEL  NICHD_Sit3_Sensitivity_NonDstrss = "NICHD_Sit3_Sensitivity_NonDistress" ;
LABEL  NICHD_Sit4_Sensitivity_NonDstrss = "NICHD_Sit4_Sensitivity_NonDistress" ;
LABEL  NICHD_Sit5_Sensitivity_NonDstrss = "NICHD_Sit5_Sensitivity_NonDistress" ;
LABEL  NICHD_post_Sit1_Sensitvty_Dstrss = "NICHD_post_Sit1_Sensitivity_Distress" ;
LABEL  NICHD_post_Sit1_Snstvty_NnDstrss = "NICHD_post_Sit1_Sensitivity_NonDistress" ;
LABEL  NICHD_post_Sit1_child_Positiv_Md = "NICHD_post_Sit1_child_Positive_Mood" ;
LABEL  NICHD_post_Sit1_child_Negativ_Md = "NICHD_post_Sit1_child_Negative_Mood" ;
LABEL  NICHD_post_Sit1_child_Sociabilty = "NICHD_post_Sit1_child_Sociability" ;
LABEL  NICHD_post_Sit2_Sensitvty_Dstrss = "NICHD_post_Sit2_Sensitivity_Distress" ;
LABEL  NICHD_post_Sit2_Snstvty_NnDstrss = "NICHD_post_Sit2_Sensitivity_NonDistress" ;
LABEL  NICHD_post_Sit2_child_Positiv_Md = "NICHD_post_Sit2_child_Positive_Mood" ;
LABEL  NICHD_post_Sit2_child_Negativ_Md = "NICHD_post_Sit2_child_Negative_Mood" ;
LABEL  NICHD_post_Sit2_child_Sociabilty = "NICHD_post_Sit2_child_Sociability" ;
LABEL  NICHD_post_Sit3_Sensitvty_Dstrss = "NICHD_post_Sit3_Sensitivity_Distress" ;
LABEL  NICHD_post_Sit3_Snstvty_NnDstrss = "NICHD_post_Sit3_Sensitivity_NonDistress" ;
LABEL  NICHD_post_Sit3_child_Positiv_Md = "NICHD_post_Sit3_child_Positive_Mood" ;
LABEL  NICHD_post_Sit3_child_Negativ_Md = "NICHD_post_Sit3_child_Negative_Mood" ;
LABEL  NICHD_post_Sit3_child_Sociabilty = "NICHD_post_Sit3_child_Sociability" ;
LABEL  NICHD_post_Sit4_Sensitvty_Dstrss = "NICHD_post_Sit4_Sensitivity_Distress" ;
LABEL  NICHD_post_Sit4_Snstvty_NnDstrss = "NICHD_post_Sit4_Sensitivity_NonDistress" ;
LABEL  NICHD_post_Sit4_child_Positiv_Md = "NICHD_post_Sit4_child_Positive_Mood" ;
LABEL  NICHD_post_Sit4_child_Negativ_Md = "NICHD_post_Sit4_child_Negative_Mood" ;
LABEL  NICHD_post_Sit4_child_Sociabilty = "NICHD_post_Sit4_child_Sociability" ;
LABEL  NICHD_post_Sit5_Sensitvty_Dstrss = "NICHD_post_Sit5_Sensitivity_Distress" ;
LABEL  NICHD_post_Sit5_Snstvty_NnDstrss = "NICHD_post_Sit5_Sensitivity_NonDistress" ;
LABEL  NICHD_post_Sit5_child_Positiv_Md = "NICHD_post_Sit5_child_Positive_Mood" ;
LABEL  NICHD_post_Sit5_child_Negativ_Md = "NICHD_post_Sit5_child_Negative_Mood" ;
LABEL  NICHD_post_Sit5_child_Sociabilty = "NICHD_post_Sit5_child_Sociability" ;
LABEL  NICHD_FU_Sit1_Sensitivity_Dstrss = "NICHD_FU_Sit1_Sensitivity_Distress" ;
LABEL  NICHD_FU_Sit1_Sensitvty_NnDstrss = "NICHD_FU_Sit1_Sensitivity_NonDistress" ;
LABEL  NICHD_FU_Sit1_child_Positive_Mod = "NICHD_FU_Sit1_child_Positive_Mood" ;
LABEL  NICHD_FU_Sit1_child_Negative_Mod = "NICHD_FU_Sit1_child_Negative_Mood" ;
LABEL  NICHD_FU_Sit2_Sensitivity_Dstrss = "NICHD_FU_Sit2_Sensitivity_Distress" ;
LABEL  NICHD_FU_Sit2_Sensitvty_NnDstrss = "NICHD_FU_Sit2_Sensitivity_NonDistress" ;
LABEL  NICHD_FU_Sit2_child_Positive_Mod = "NICHD_FU_Sit2_child_Positive_Mood" ;
LABEL  NICHD_FU_Sit2_child_Negative_Mod = "NICHD_FU_Sit2_child_Negative_Mood" ;
LABEL  NICHD_FU_Sit3_Sensitivity_Dstrss = "NICHD_FU_Sit3_Sensitivity_Distress" ;
LABEL  NICHD_FU_Sit3_Sensitvty_NnDstrss = "NICHD_FU_Sit3_Sensitivity_NonDistress" ;
LABEL  NICHD_FU_Sit3_child_Positive_Mod = "NICHD_FU_Sit3_child_Positive_Mood" ;
LABEL  NICHD_FU_Sit3_child_Negative_Mod = "NICHD_FU_Sit3_child_Negative_Mood" ;
LABEL  NICHD_FU_Sit4_Sensitivity_Dstrss = "NICHD_FU_Sit4_Sensitivity_Distress" ;
LABEL  NICHD_FU_Sit4_Sensitvty_NnDstrss = "NICHD_FU_Sit4_Sensitivity_NonDistress" ;
LABEL  NICHD_FU_Sit4_child_Positive_Mod = "NICHD_FU_Sit4_child_Positive_Mood" ;
LABEL  NICHD_FU_Sit4_child_Negative_Mod = "NICHD_FU_Sit4_child_Negative_Mood" ;
LABEL  NICHD_FU_Sit5_Sensitivity_Dstrss = "NICHD_FU_Sit5_Sensitivity_Distress" ;
LABEL  NICHD_FU_Sit5_Sensitvty_NnDstrss = "NICHD_FU_Sit5_Sensitivity_NonDistress" ;
LABEL  NICHD_FU_Sit5_child_Positive_Mod = "NICHD_FU_Sit5_child_Positive_Mood" ;
LABEL  NICHD_FU_Sit5_child_Negative_Mod = "NICHD_FU_Sit5_child_Negative_Mood" ;
LABEL  SSP_Pre_three_way_secure_or_nscr = "SSP_Pre_three_way_secure_or_insecure" ;
LABEL  SSP_Pre_four_way_rgnzd_r_dsrgnzd = "SSP_Pre_four_way_organized_or_disorganized" ;
LABEL  SSP_Post__three_way_classificatn = "SSP_Post__three_way_classification" ;
LABEL  SSP_Post_three_way_secure_r_nscr = "SSP_Post_three_way_secure_or_insecure" ;
LABEL  SSP_Post__four_way_classificatin = "SSP_Post__four_way_classification" ;
LABEL  SSP_Post_four_wy_rgnzd_r_dsrgnzd = "SSP_Post_four_way_organized_or_disorganized" ;
LABEL  NICHD_Sensitivity_to_distrss_ttl = "NICHD_Sensitivity_to_distress_total" ;
LABEL  NICHD_Sensitivity_nondistrss_ttl = "NICHD_Sensitivity_nondistress_total" ;
LABEL  NICHD_mother_negatv_ttl_REVERSED = "NICHD_mother_negative_total_REVERSED" ;
LABEL  NICHD_Child_Negativ_ttl_REVERSED = "NICHD_Child_Negative_total_REVERSED" ;
LABEL  post_NICHD_Senstvty_t_dstrss_ttl = "post_NICHD_Sensitivity_to_distress_total" ;
LABEL  post_NICHD_Senstvty_nndstrss_ttl = "post_NICHD_Sensitivity_nondistress_total" ;
LABEL  post_NICHD_Child_sociability_ttl = "post_NICHD_Child_sociability_total" ;
LABEL  post_NICHD_Intrusiv_ttl_REVERSED = "post_NICHD_Intrusive_total_REVERSED" ;
LABEL  post_NICHD_Detchmnt_ttl_REVERSED = "post_NICHD_Detachment_total_REVERSED" ;
LABEL  pst_NICHD_mthr_ngtv_ttl_REVERSED = "post_NICHD_mother_negative_total_REVERSED" ;
LABEL  pst_NICHD_Chld_Ngtv_ttl_REVERSED = "post_NICHD_Child_Negative_total_REVERSED" ;
LABEL  FU_NICHD_Sensitivty_t_dstrss_ttl = "FU_NICHD_Sensitivity_to_distress_total" ;
LABEL  FU_NICHD_Sensitivty_nndstrss_ttl = "FU_NICHD_Sensitivity_nondistress_total" ;
LABEL  FU_NICHD_Intrusive_totl_REVERSED = "FU_NICHD_Intrusive_total_REVERSED" ;
LABEL  FU_NICHD_Detachment_ttl_REVERSED = "FU_NICHD_Detachment_total_REVERSED" ;
LABEL  FU_NICHD_mothr_ngtv_ttl_REVERSED = "FU_NICHD_mother_negative_total_REVERSED" ;
LABEL  FU_NICHD_Child_Ngtv_ttl_REVERSED = "FU_NICHD_Child_Negative_total_REVERSED" ;
FORMAT Pre_Ax_1_Date yymmdd10.;
FORMAT Pre_Ax_2_Date yymmdd10.;
FORMAT Pre_Home_Visit_Date yymmdd10.;
FORMAT Date_ASD_Ax yymmdd10.;
FORMAT Date_Pre_questionnaires yymmdd10.;
FORMAT DOBchild yymmdd10.;
FORMAT DOBmo yymmdd10.;
FORMAT DOBfa yymmdd10.;
RUN;
